# Generated by Django 5.2.14 on 2026-05-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ingreso_neto_mensual',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='situacion_laboral',
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento_identidad',
            field=models.CharField(default=1, max_length=11, unique=True, verbose_name='Número de Documento (DNI/RUC)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='ingreso_mensual',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Ingreso Neto / Facturación Mensual (S/.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón Social / Empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('NATURAL', 'Persona Natural'), ('JURIDICA', 'Persona Jurídica / Entidad')], default='NATURAL', max_length=10, verbose_name='Tipo de Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono Celular / Contacto'),
        ),
    ]
