# Generated by Django 5.2.14 on 2026-05-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_remove_cliente_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Entidad Financiera')),
                ('tea', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa Efectiva Anual (TEA %)')),
                ('tasa_desgravamen', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Seguro de Desgravamen Mensual (%)')),
                ('tasa_seguro_vehicular', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Seguro Vehicular Anual (%)')),
                ('comision_portes', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Comisión por Portes / Envío de Estado de Cuenta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'bancos',
            },
        ),
    ]
