# Generated by Django 5.2.14 on 2026-05-30 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_banco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(choices=[('PEN', 'Soles (S/.)'), ('USD', 'Dólares ($)')], default='PEN', max_length=3, verbose_name='Moneda del Préstamo')),
                ('tipo_cambio', models.DecimalField(decimal_places=2, default=3.75, max_digits=4, verbose_name='Tipo de Cambio Aplicado')),
                ('cuota_inicial_porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cuota Inicial (%)')),
                ('cuota_balon_porcentaje', models.DecimalField(decimal_places=2, default=40.0, max_digits=5, verbose_name='Cuota Balón / Valor Residual (%)')),
                ('plazo_meses', models.IntegerField(choices=[(24, '24 Meses'), (36, '36 Meses')], default=36, verbose_name='Plazo del Crédito')),
                ('meses_gracia', models.IntegerField(default=0, verbose_name='Meses de Gracia (0 a 3)')),
                ('tipo_gracia', models.CharField(choices=[('SIN_GRACIA', 'Sin Periodo de Gracia'), ('PARCIAL', 'Gracia Parcial (Pago de Interés Puro)'), ('TOTAL', 'Gracia Total (Capitalización de Interés)')], default='SIN_GRACIA', max_length=15, verbose_name='Modalidad de Gracia')),
                ('tcea_calculada', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='TCEA Real (%)')),
                ('van_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='VAN Generado')),
                ('tir_calculada', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='TIR (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.banco', verbose_name='Banco Financiador')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.cliente', verbose_name='Cliente Evaluado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.vehiculo', verbose_name='Vehículo de Interés')),
            ],
            options={
                'verbose_name': 'Simulación',
                'verbose_name_plural': 'Simulaciones',
                'db_table': 'simulaciones',
            },
        ),
    ]
